<?php
// Založeno 29.4.2023
?>
<h1>Seznam uživatelů</h1>

<table>
    <?php foreach ($uzivatele as $uzivatel): ?>
        <tr>
            <td>
                
                <h2><a href="uzivatel/    
                <?= $uzivatel['telefon'] ?>">
                <?= $uzivatel['cele_jmeno'] ?></a></h2>
                <?= $uzivatel['rodne_cislo'] ?>
                 
                <!-- Adresu mozo odstranit dela chyby -->
                <?php if ($admin): ?>
                    <br />
                    <a href="editoruzivatelu/<?= $uzivatel['uzivatele_id'] ?>">Editovat</a>
                    <a href="uzivatel/<?= $uzivatel['uzivatele_id'] ?>/odstranit">Odstranit</a>
                <?php endif ?>

            </td>
        </tr>
    <?php endforeach ?>
</table>
<table>
<?php foreach ($uzivatele as $uzivatel): ?>
        <tr>
            <th>Jméno</th>
            <th>Telefon</th>
            <th>Rodné číslo</th>
        </tr>
        <tr>
            <td><?= $uzivatel['cele_jmeno'] ?></td>
            <td><?= $uzivatel['telefon'] ?></td>
            <td><?= $uzivatel['rodne_cislo'] ?></td>
        </tr>
        
        <?php endforeach ?>
    </table>

   